### ISSUE TITLE
'DataFrame' object has no attribute 'as_matrix'

### ISSUE THREAD

**Issue by chansigit** [aertslab/SCENIC#135]
pyscenic grn 200409-ABM2-totalclustered.scenic.expression.csv /data/hca/public_data/scenic/mm_mgi_tfs.txt -o 200409-ABM2-totalclustered.scenic.adjacencies.tsv --num_workers 1

I got 'DataFrame' object has no attribute 'as_matrix'
Do I use the wrong version of pandas?

/var/lib/hcaadmin/anaconda1907/envs/r36/lib/python3.8/site-packages/dask/config.py:161: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/var/lib/hcaadmin/anaconda1907/envs/r36/lib/python3.8/site-packages/dask/dataframe/utils.py:13: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm
2020-05-15 12:48:31,658 - pyscenic.cli.pyscenic - INFO - Loading expression matrix.
2020-05-15 12:48:47,423 - pyscenic.cli.pyscenic - INFO - Inferring regulatory networks.
/var/lib/hcaadmin/anaconda1907/envs/r36/lib/python3.8/site-packages/dask/config.py:161: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.  data = yaml.load(f.read()) or {}
/var/lib/hcaadmin/anaconda1907/envs/r36/lib/python3.8/site-packages/dask/dataframe/utils.py:13: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm
preparing dask client
parsing input
not shutting down client, client was created externallyfinished
Traceback (most recent call last):
  File "/var/lib/hcaadmin/anaconda1907/envs/r36/bin/pyscenic", line 8, in <module>    sys.exit(main())
  File "/var/lib/hcaadmin/anaconda1907/envs/r36/lib/python3.8/site-packages/pyscenic/cli/pyscenic.py", line 420, in main
    args.func(args)
  File "/var/lib/hcaadmin/anaconda1907/envs/r36/lib/python3.8/site-packages/pyscenic/cli/pyscenic.py", line 72, in find_adjacencies_command
    network = method(expression_data=ex_mtx, tf_names=tf_names, verbose=True, client_or_address=client, seed=args.seed)
  File "/var/lib/hcaadmin/anaconda1907/envs/r36/lib/python3.8/site-packages/arboreto/algo.py", line 39, in grnboost2
    return diy(expression_data=expression_data, regressor_type='GBM', regressor_kwargs=SGBM_KWARGS,
  File "/var/lib/hcaadmin/anaconda1907/envs/r36/lib/python3.8/site-packages/arboreto/algo.py", line 115, in diy
    expression_matrix, gene_names, tf_names = _prepare_input(expression_data, gene_names, tf_names)
  File "/var/lib/hcaadmin/anaconda1907/envs/r36/lib/python3.8/site-packages/arboreto/algo.py", line 214, in _prepare_input
    expression_matrix = expression_data.as_matrix()
  File "/var/lib/hcaadmin/anaconda1907/envs/r36/lib/python3.8/site-packages/pandas/core/generic.py", line 5274, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'as_matrix'

**Comment by chansigit** [comment]
It should be asked in pySCENIC repo
